apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T11:13:30Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3299"
  uid: a75fbaa0-5130-4ed1-a8bc-e0f947f72c03
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.157.41
  clusterIPs:
  - 10.104.157.41
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31231
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
